<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SUBHASHA-PC" name="com.jbk.owp.test.LoginTest" tests="11" failures="1" timestamp="21 Jan 2020 08:36:23 GMT" time="4.208" errors="0">
  <testcase name="verifyUrl" time="0.129" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyApplicationTitle" time="0.087" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyTitle" time="0.120" classname="com.jbk.owp.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Java By subhash] but found [Java By Kiran]">
      <![CDATA[java.lang.AssertionError: expected [Java By subhash] but found [Java By Kiran]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.jbk.owp.test.LoginTest.verifyTitle(LoginTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyTitle -->
  <testcase name="verifyloginsesion" time="0.112" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyPlaceHolderUsername" time="0.088" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyPlaceHolderPassword" time="0.306" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyButtoncolor" time="0.240" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="verifyLinks" time="0.107" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="Login" time="0.800" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="Login" time="0.427" classname="com.jbk.owp.test.LoginTest"/>
  <testcase name="Login" time="1.792" classname="com.jbk.owp.test.LoginTest"/>
</testsuite> <!-- com.jbk.owp.test.LoginTest -->
